import type { ProductRecord } from './types'
import { MOCK_SKILL1, MOCK_SKILL2, MOCK_SKILL3, MOCK_SKILL4, MOCK_SKILL5, MOCK_SKILL6 } from './mock-data'

export const MOCK_PRODUCT_HISTORY: ProductRecord[] = [
  {
    id: 'prod-demo-001',
    name: '法式碎花 V 领连衣裙',
    category: '女装-连衣裙',
    priceRange: '100-300',
    createdAt: '2026-03-20T10:30:00.000Z',
    healthScore: 74,
    completedSkills: [1, 2, 3, 4, 5, 6],
    session: {
      productInput: { category: '女装-连衣裙', priceRange: '100-300', styleKeywords: ['法式', '通勤'], costPrice: 68 },
      skill1: MOCK_SKILL1,
      selectedStyle: MOCK_SKILL1.recommendations[0],
      skill2: MOCK_SKILL2,
      skill3: MOCK_SKILL3,
      skill4: MOCK_SKILL4,
      skill5: MOCK_SKILL5,
      skill6: MOCK_SKILL6,
    },
    changeLog: [
      {
        id: 'ev-001-1',
        skillId: 1,
        skillLabel: 'AI 找款',
        changeType: 'style_selection',
        changedAt: '2026-03-20T10:32:00.000Z',
        summary: '选款：法式碎花 V 领连衣裙（S 级）',
        metricBefore: {},
        status: 'measured',
      },
      {
        id: 'ev-001-2',
        skillId: 2,
        skillLabel: '上架优化',
        changeType: 'title',
        changedAt: '2026-03-20T10:45:00.000Z',
        summary: '修改标题 v1 → v2（搜索导向）',
        metricBefore: { ctr: 2.1, cvr: 0.6 },
        metricAfter: { ctr: 4.1, cvr: 0.9 },
        impact: 'CTR +95%，标题关键词覆盖度提升',
        nextAction: 'CVR 仍偏低，建议优化主图',
        status: 'measured',
      },
      {
        id: 'ev-001-3',
        skillId: 3,
        skillLabel: '智能定价',
        changeType: 'price',
        changedAt: '2026-03-21T09:00:00.000Z',
        summary: '调价 199 元 → 169 元（新品引流价）',
        metricBefore: { dailySales: 5, cvr: 0.6 },
        metricAfter: { dailySales: 12, cvr: 1.1 },
        impact: '日销 +140%，CVR +83%，Lagrangian 预测验证',
        nextAction: '第16天可调回 189 元（成长期）',
        status: 'measured',
      },
      {
        id: 'ev-001-4',
        skillId: 4,
        skillLabel: '评价诊断',
        changeType: 'sku_desc',
        changedAt: '2026-03-28T14:00:00.000Z',
        summary: 'P0：SKU 说明加入"M码偏小"提示',
        metricBefore: { returnRate: 0.18, positiveRate: 0.79 },
        metricAfter: { returnRate: 0.12, positiveRate: 0.84 },
        impact: '退货率 -33%，好评率 +6%',
        status: 'measured',
      },
      {
        id: 'ev-001-5',
        skillId: 5,
        skillLabel: '推广诊断',
        changeType: 'keyword_bid',
        changedAt: '2026-04-01T08:30:00.000Z',
        summary: '暂停"连衣裙女" / 提升"法式碎花裙"出价',
        metricBefore: { roi: 1.8, dailyAdSpend: 430 },
        metricAfter: { roi: 2.4, dailyAdSpend: 250 },
        impact: 'ROI +33%，日广告费节省 ¥180',
        nextAction: '继续观察 3 天，达到 2.6 目标',
        status: 'measured',
      },
      {
        id: 'ev-001-6',
        skillId: 2,
        skillLabel: '上架优化',
        changeType: 'main_image',
        changedAt: '2026-04-05T09:00:00.000Z',
        summary: '更换主图 v1 → v2（场景穿搭图换首位）',
        metricBefore: { ctr: 4.1 },
        status: 'pending',
        nextAction: '等待 7 天数据，预计 2026-04-12 可见效果',
      },
    ],
    currentMetrics: { ctr: 4.1, cvr: 1.1, dailySales: 12, positiveRate: 0.84, roi: 2.4 },
  },
  {
    id: 'prod-demo-002',
    name: '新中式盘扣提花连衣裙',
    category: '女装-连衣裙',
    priceRange: '150-400',
    createdAt: '2026-03-15T14:00:00.000Z',
    healthScore: 58,
    completedSkills: [1, 2, 3],
    session: {
      productInput: { category: '女装-连衣裙', priceRange: '150-400', styleKeywords: ['新中式'], costPrice: 95 },
      skill1: MOCK_SKILL1,
      selectedStyle: MOCK_SKILL1.recommendations[1],
    },
    changeLog: [
      {
        id: 'ev-002-1',
        skillId: 1,
        skillLabel: 'AI 找款',
        changeType: 'style_selection',
        changedAt: '2026-03-15T14:05:00.000Z',
        summary: '选款：新中式盘扣提花连衣裙（S 级）',
        metricBefore: {},
        status: 'measured',
      },
      {
        id: 'ev-002-2',
        skillId: 3,
        skillLabel: '智能定价',
        changeType: 'price',
        changedAt: '2026-03-16T09:00:00.000Z',
        summary: '新品定价 229 元',
        metricBefore: {},
        metricAfter: { dailySales: 4, cvr: 0.5 },
        impact: '日销低于 S_F1 预期（模型预测 >15），可能竞争强度超预期',
        nextAction: '建议运行 Skill 4 评价诊断，排查上架内容问题',
        status: 'measured',
      },
    ],
    currentMetrics: { ctr: 1.8, cvr: 0.5, dailySales: 4, positiveRate: 0.78, roi: 1.1 },
  },
  {
    id: 'prod-demo-003',
    name: '薄荷曼波色系背心裙',
    category: '女装-连衣裙',
    priceRange: '80-180',
    createdAt: '2026-04-01T11:00:00.000Z',
    healthScore: 41,
    completedSkills: [1],
    session: {
      productInput: { category: '女装-连衣裙', priceRange: '80-180', styleKeywords: ['极简', '夏季'], costPrice: 32 },
      skill1: MOCK_SKILL1,
      selectedStyle: MOCK_SKILL1.recommendations[2],
    },
    changeLog: [
      {
        id: 'ev-003-1',
        skillId: 1,
        skillLabel: 'AI 找款',
        changeType: 'style_selection',
        changedAt: '2026-04-01T11:08:00.000Z',
        summary: '选款：薄荷曼波色系背心裙（A 级）',
        metricBefore: {},
        status: 'pending',
        nextAction: '尚未上架，建议运行 Skill 2 生成上架包',
      },
    ],
    currentMetrics: {},
  },
]
